[package]
name = "devnet"
version.workspace = true
edition.workspace = true

[[bin]]
name = "devnet"
path = "src/bin/devnet.rs"

[dependencies]
rift-core = { workspace = true }
rift-sdk = { workspace = true }
bitcoin-light-client-core = { workspace = true }
data-engine = { workspace = true }
data-engine-server = { workspace = true }
corepc-node = { workspace = true }


alloy = { workspace = true }
clap = { workspace = true }
bitcoin = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
bitcoincore-rpc-async = { workspace = true }