[package]
name = "market-maker"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
exclude.workspace = true

[dependencies]
rift-sdk = { workspace = true }
bitcoin-light-client-core = { workspace = true }
bitcoin = { workspace = true }
data-engine = { workspace = true }
rift-core = { workspace = true }
sol-types = { workspace = true }
bitcoincore-rpc-async2 = { workspace = true }
checkpoint-downloader = { workspace = true }


reqwest = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rusqlite = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
alloy = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
chrono = { workspace = true }