[package]
name = "hypernode"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hypernode"
path = "src/main.rs"

[dependencies]
sol-types = { workspace = true }
bitcoin-core-rs = { workspace = true }
bitcoin-light-client-core = { workspace = true }
bitcoin-data-engine = { workspace = true }
rift-core = { workspace = true }
rift-sdk = { workspace = true }
rift-program = { workspace = true }
data-engine = { workspace = true }
checkpoint-downloader = { workspace = true }
bitcoincore-rpc-async2 = { workspace = true }

tokio = { workspace = true }
alloy = { workspace = true }
futures-util = { workspace = true }
eyre = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
futures = { workspace = true }
env_logger = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
bitcoin = { workspace = true }
crypto-bigint = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }