[package]
version = "0.1.0"
name = "btc-light-client-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
btc-light-client-core = { path = "../core" }